In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

In [3]:
# Read in the CSV file as a pandas DataFrame
df = pd.read_csv('Resources/model_car_prices_no_mmr.csv')

# Review the DataFrame
df.head()

   year  make   body  color  interior  sellingprice  odometer  automatic
0  2015    18    SUV     17         1       21500.0   16639.0       True
1  2015    18    SUV     17         0       21500.0    9393.0       True
2  2014     2  Sedan      8         1       30000.0    1331.0       True
3  2015    40  Sedan     17         1       27750.0   14282.0       True
4  2014     2  Sedan      8         1       67000.0    2641.0       True

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd

# Function to remove outliers for given columns
def remove_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]

# Assuming df is your DataFrame

# List of unique body types
unique_bodies = ['SUV', 'Sedan', 'Convertible', 'Coupe', 'Wagon', 'Hatchback', 'Crew_Truck', 'Minivan', 'Van', 'Ext_Truck', 'Truck']

# Features to include
features = ['odometer', 'year', 'make', 'color', 'interior', 'automatic']  # Assuming 'automatic' is already numeric

# Loop through each unique body type
for body_type in unique_bodies:
    print(f"Results for body type: {body_type}")
    
    # Filter the DataFrame for the current body type
    df_body = df[df['body'] == body_type]

    # Remove outliers from the 'odometer' column
    df_body = remove_outliers(df_body, 'odometer')
  
    # Set up X and y
    X = df_body[features]
    y = df_body["sellingprice"]
    
    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # Create the model
    model = LinearRegression()
    
    # Fit the model to the training data
    model.fit(X_train, y_train)
    
    # Predict on the testing set
    predicted = model.predict(X_test)
    
    # Calculate the MSE and R2
    mse = mean_squared_error(y_test, predicted)
    r2 = r2_score(y_test, predicted)
    
    # Print the results
    print(f"Mean squared error (MSE) for {body_type}: {mse:.2f}")
    print(f"R-squared (R2) for {body_type}: {r2:.2f}\n")

Results for body type: SUV
Mean squared error (MSE) for SUV: 51325759.23
R-squared (R2) for SUV: 0.52

Results for body type: Sedan
Mean squared error (MSE) for Sedan: 34067843.87
R-squared (R2) for Sedan: 0.42

Results for body type: Convertible
Mean squared error (MSE) for Convertible: 105079234.63
R-squared (R2) for Convertible: 0.49

Results for body type: Coupe
Mean squared error (MSE) for Coupe: 86970194.86
R-squared (R2) for Coupe: 0.45

Results for body type: Wagon
Mean squared error (MSE) for Wagon: 20105675.79
R-squared (R2) for Wagon: 0.64

Results for body type: Hatchback
Mean squared error (MSE) for Hatchback: 17702861.50
R-squared (R2) for Hatchback: 0.39

Results for body type: Crew_Truck
Mean squared error (MSE) for Crew_Truck: 34171945.54
R-squared (R2) for Crew_Truck: 0.67

Results for body type: Minivan
Mean squared error (MSE) for Minivan: 10423162.19
R-squared (R2) for Minivan: 0.79

Results for body type: Van
Mean squared error (MSE) for Van: 6392100.97
R-squared (R2) for Van: 0.88

Results for body type: Ext_Truck
Mean squared error (MSE) for Ext_Truck: 12008786.04
R-squared (R2) for Ext_Truck: 0.79

Results for body type: Truck
Mean squared error (MSE) for Truck: 9801546.29
R-squared (R2) for Truck: 0.77